[project]
name = "parse-ppt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markitdown>=0.1.3",
    "openaivec>=1.0.0",
]
